export interface IData {
    rowid: number,
    orderId: string,
    orderDate: Date,
    shipdate: Date,
    shipMode: string,
    customerId: string,
    customerName: string,
    segment: string,
    country: string,
    city: string,
    state: string,
    postalCode: string,
    region: string,
    productId: string,
    categoty: string,
    subCategory: string,
    productname: string,
    sales: number,
    quantity: number,
    discount: number,
    profit: number,
}